### ISSUE TITLE
Выражаю искреннюю благодарность за Ваш проект

### ISSUE THREAD

**Issue by snkreg** [y3401/parser-torrent-db#1]
Очень нужная вещь, спасибо Вам.
Вопрос - не смог запустить с первого раза:
 parser-torrent-db-master python sax_parser.py    
Traceback (most recent call last):
  File "sax_parser.py", line 8, in <module>
    import modsql3 as lite
  File "/home/roman/Загрузки/base_torrent/parser-torrent-db-master/modsql3.py", line 6, in <module>
    import modbbcode
ImportError: No module named modbbcode

Подскажите, будьте добры - в чем причина? Я не могу найти modbbcode. Как только ни пробовал - выдает ошибку:
"Collecting modbbcode
  Could not find a version that satisfies the requirement modbbcode (from versions: )
No matching distribution found for modbbcode"

Сориентируйте, пожалуйста. Мне интересен Ваш труд. хочу базу себе по категориям разбить и структурировать все.
Благодарю

**Comment by y3401** [comment]
Доброго времени суток!
Добавил этот модуль в этот проект, хотя он тут не сильно нужен - этот модуль был нужен для отладки, пока писал InfoTor (там этот модуль работает в полную силу).  
 Реально можно убрать импорт modbbcode и закомментировать функцию def sel_content(...), в которой оно вызывается.
